version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/
    depends_on:
      - php-fpm
      - php-fpm-respaldo
      - database
    ports:
      - "80:80"
    networks:
      - php-stack

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/
    depends_on:
      - database
    networks:
      - php-stack
  
  php-fpm-respaldo:
    build:
      context: ./php-fpm
    container_name: php-fpm-respaldo
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/
    depends_on:
      - database
    networks:
      - php-stack

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - TZ=Spain/Madrid
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - php-stack

  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=tienda
      - MYSQL_USER=myadmin
      - MYSQL_PASSWORD=abc123.
      - MYSQL_ROOT_PASSWORD=abc123.
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    networks:
      - php-stack

networks:
  php-stack:
    name: php-stack
